import Foundation
import SwiftUI

/// Tracks free-tier usage and decides when to gate Pro features.
///
/// Free quotas (lifetime, persisted via UserDefaults):
///   - AI meal scans: 3
///   - Barcode product scans: 5
///
/// Pro-only (no free usage):
///   - Manual Sunday Calibration re-run
///
/// The automatic weekly Sunday Calibration generated by the app is NOT gated —
/// only manually triggered re-runs require Pro.
@MainActor
enum EntitlementGate {
    static let mealScanFreeQuota = 3
    static let barcodeScanFreeQuota = 5

    private static let mealScanKey = "freeMealScansUsed"
    private static let barcodeScanKey = "freeBarcodeScansUsed"

    // MARK: - Counters

    static var mealScansUsed: Int {
        UserDefaults.standard.integer(forKey: mealScanKey)
    }

    static var barcodeScansUsed: Int {
        UserDefaults.standard.integer(forKey: barcodeScanKey)
    }

    static func recordMealScan() {
        UserDefaults.standard.set(mealScansUsed + 1, forKey: mealScanKey)
    }

    static func recordBarcodeScan() {
        UserDefaults.standard.set(barcodeScansUsed + 1, forKey: barcodeScanKey)
    }

    // MARK: - Decisions

    /// Returns true if the user can perform another AI meal scan without Pro.
    static func canScanMeal(isPremium: Bool) -> Bool {
        isPremium || mealScansUsed < mealScanFreeQuota
    }

    /// Returns true if the user can perform another barcode scan without Pro.
    static func canScanBarcode(isPremium: Bool) -> Bool {
        isPremium || barcodeScansUsed < barcodeScanFreeQuota
    }

    /// Returns the number of free AI meal scans remaining (capped at 0).
    static func mealScansRemaining(isPremium: Bool) -> Int {
        isPremium ? Int.max : max(0, mealScanFreeQuota - mealScansUsed)
    }

    /// Returns the number of free barcode scans remaining (capped at 0).
    static func barcodeScansRemaining(isPremium: Bool) -> Int {
        isPremium ? Int.max : max(0, barcodeScanFreeQuota - barcodeScansUsed)
    }
}
