import SwiftUI

/// Warm parchment card showing today's PhD directive.
/// 15-word focus generated by Gemini, refreshed once per day.
struct DailyDirectiveCard: View {
    let directive: String
    let isLoading: Bool
    var onTap: () -> Void = {}

    @State private var pressed: Bool = false

    var body: some View {
        Button(action: {
            UIImpactFeedbackGenerator(style: .soft).impactOccurred()
            onTap()
        }) {
            VStack(alignment: .leading, spacing: 8) {
                HStack(spacing: 8) {
                    Image(systemName: "sparkle")
                        .font(.system(size: 11, weight: .bold))
                        .foregroundStyle(PrecisionCalTheme.terracotta)
                    Text("PRECISIONCAL · TODAY'S FOCUS")
                        .font(.system(size: 10, weight: .semibold))
                        .tracking(2)
                        .foregroundStyle(PrecisionCalTheme.terracotta)
                }
                ZStack(alignment: .leading) {
                    if isLoading && directive.isEmpty {
                        HStack(spacing: 12) {
                            BreathingOrb(size: 28)
                            Text("Composing your daily focus…")
                                .font(.system(size: 14, weight: .medium))
                                .foregroundStyle(PrecisionCalTheme.textSecondary)
                        }
                        .padding(.vertical, 4)
                        .transition(.opacity)
                        .id("loading")
                    } else {
                        Text(directive.isEmpty
                             ? "Begin gently. Hydrate, breathe, and choose one nourishing meal today."
                             : directive)
                            .font(.custom("Georgia-Italic", size: 17))
                            .foregroundStyle(PrecisionCalTheme.textPrimary)
                            .lineSpacing(3)
                            .multilineTextAlignment(.leading)
                            .transition(.opacity)
                            .id(directive.isEmpty ? "placeholder" : directive)
                    }
                }
                .animation(.easeInOut(duration: 0.8), value: directive)
                .animation(.easeInOut(duration: 0.8), value: isLoading)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(18)
            .background {
                RoundedRectangle(cornerRadius: 22, style: .continuous)
                    .fill(Color(red: 0xFD/255, green: 0xFB/255, blue: 0xF7/255))
                    .overlay(
                        RoundedRectangle(cornerRadius: 22, style: .continuous)
                            .stroke(PrecisionCalTheme.glassStroke.opacity(0.7), lineWidth: 1)
                    )
                    .shadow(color: PrecisionCalTheme.terracotta.opacity(0.05),
                            radius: 12, x: 0, y: 6)
            }
            .scaleEffect(pressed ? 0.985 : 1)
            .animation(.spring(response: 0.3, dampingFraction: 0.7), value: pressed)
        }
        .buttonStyle(PressButtonStyle(isPressed: $pressed))
        .gentleWaveRipple()
    }
}
